#!/usr/bin/env bash
# Script to install and configure Nginx on Ubuntu

sudo apt-get update
sudo apt-get install nginx -y
echo "server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }

}" > /etc/nginx/sites-available/default

echo "<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>" > /var/www/html/index.html

kill -s HUP $(pgrep nginx)