#!/usr/bin/env bash
# This script configures the hosts file on an Ubuntu server.

localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

sudo sed -i "s/^\(127.0.0.1\s\+localhost\)/\1\n${localhost_ip} localhost/g" /etc/hosts
sudo sed -i "s/^\(0.0.0.0\s\+facebook.com\)/\1\n${facebook_ip} facebook.com/g" /etc/hosts

